### ISSUE TITLE
Help! Some problems when I re-run the code😭

### ISSUE THREAD

**Issue by ysj-qc** [vivian1993/NCRL#12]
Dear Vivian1993! I have read your paper and understand what you introduced in it. But I have some problems in reproducing. I’m new to coding and still learning the ropes.
I have re-run your code "main.py" by terminal, and it seems has already trained a model and stored in my computer, but when I turned to run "kg_completion.py" with command: 

"python kg_completion.py --data family --rule family --cpu_num 8  --batch_size 1 --top 200 --threshold 0", 

then error occurred, which said: "Traceback (most recent call last):
  File "kg_completion.py", line 228, in <module>
    load_rules("{}".format(file), all_rules, all_rule_heads)
  File "kg_completion.py", line 86, in load_rules
    with open(rule_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'family\\family_500_2.txt'"

and same situation occurred in my re-run process in "generate_rule.py" with command:

"python generate_rule.py --data family --topk 10 --phb --gpu 0",

error information said:
"Traceback (most recent call last):
  File "generate_rule.py", line 166, in <module>
    generate_phb_matrix(args, dataset)
  File "generate_rule.py", line 83, in generate_phb_matrix
    with open('..\\results\\model_True', 'rb') as g:
FileNotFoundError: [Errno 2] No such file or directory: '..\\results\\model_True'"

I'm really interested in your work on KG reasoning, and I'm totally new in CS and python, so I'm looking forward to your reply! 
![屏幕截图 2024-03-14 163955](https://github.com/vivian1993/NCRL/assets/83745703/262779dc-c431-4654-9217-dd0ec1cc6c59)
![屏幕截图 2024-03-14 164007](https://github.com/vivian1993/NCRL/assets/83745703/49ca6390-e3c5-4c68-a9e1-d7d20a9599f9)

**Comment by vivian1993** [comment]
Make sure that you indeed get the file "family\family_500_2.txt" after running main.py
