### ISSUE TITLE
Confusion of the parser.

### ISSUE THREAD

**Issue by rabi-fei** [vivian1993/NCRL#2]
Hi, the work is pretty cool. I have read the code carefully and want to apply this model to other datasets. But there is some confusion about the parser. I guess the output of the parser is the h, r, t and the (h, r, t) is a fact triple. But the function seems to do the something reverse and output the (t, r, h). I am uncertain whether I get some misunderstandings and don't know the right effect of the function. 

 I would appreciate it if you could provide some clarification on this matter.

The following is the related code.
def parse_rdf(rdf):
    """
        return: head, relation, tail
    """
    rdf_tail, rdf_rel, rdf_head = rdf
    return rdf_head, rdf_rel, rdf_tail

**Comment by shannon-paul** [comment]
> 
Hey I'm also confused about parse_rdf here, if you figure out why, can you add an answer here? thanks :)

**Comment by rabi-fei** [comment]
> Hey I'm also confused about parse_rdf here, if you figure out why, can you add an answer here? thanks :)

Sure, if I have figured it :)

**Comment by burning5112** [comment]
whats the reason？

**Comment by RManLuo** [comment]
Same question

**Comment by vivian1993** [comment]
This is used to compute the (?, r, t) query

**Comment by vivian1993** [comment]
This is used to compute the (?, r, t) query
