### ISSUE TITLE
关于kg_completion.py脚本运行时内存不足的问题

### ISSUE THREAD

**Issue by shannon-paul** [vivian1993/NCRL#3]
您好，感谢您做出的出色工作，在使用kg_completion.py使用规则去evaluate FB15K-237这种比较大的数据集的时候，由于需要构建超大的矩阵，会导致内存不足（使用260G内存的服务器也无法满足需求），请问该如何解决呢，谢谢！

**Comment by hardwayrightway** [comment]
您是怎么解决这个问题的？求教，我能想到的就是生成rule时分段写，但改动似乎挺多的。

**Comment by shannon-paul** [comment]
> 您是怎么解决这个问题的？求教，我能想到的就是生成rule时分段写，但改动似乎挺多的。

代码更新了，新的代码更改了一些稀疏矩阵的操作，就没这个问题了:)

**Comment by hardwayrightway** [comment]
多谢
