### ISSUE TITLE
Some issues arising from reproducing papers

### ISSUE THREAD

**Issue by oier991215** [vivian1993/NCRL#5]
Hello author, I am very interested in your paper and have encountered some questions while reproducing the paper dataset. I hope you can answer them. Thank you very much.

Taking the knowledge graph completion task and the Family dataset as examples, I set

Batch_ Size=500
Embedding_ Dim=512
Epochs=1000
Max_ Path_ Len=3
Learning_ Rate=0.0001
Topk=500,
The parameter 'Open Paths Sampling Ratio' should be set to 0.1, but I cannot find the corresponding position in the code.

After following the above configuration, I successively ran "main. py" and "kg_completion. py", but the replication effect was poor.

What are the meanings of the parameters' sparsity ',' alpha ',' anchor ',' learned_path_len ', and' top 'and' threshold 'in' main. py 'and' kg_completion. py '? Do you follow the initial settings?

**Comment by vivian1993** [comment]
The parameter 'Open Paths Sampling Ratio' can be found in data.py "rule_head_rel == False and random.random() > 0.9" (1-Open Paths Sampling Ratio)

the parameters
sparsity is used to randomly drop some triples to make the graph to be sparse
alpha is used to balance the prediction for rule head  and entropy of the prediction
anchor is used to sample paths from KG
learned_path_len is used to set the limit the length of generated rules
top is used to select top n rule from the generated rules
threshold is used to drop the rules whose confidence is below some threshold.

When completing KG, we can use either the rule of length 2, the rule of length 3, and rule of length 4 or use any combination of them to complete the graph. Pick the best one.

**Comment by DD22333** [comment]
> Hello author, I am very interested in your paper and have encountered some questions while reproducing the paper dataset. I hope you can answer them. Thank you very much.
> 
> Taking the knowledge graph completion task and the Family dataset as examples, I set
> 
> Batch_ Size=500 Embedding_ Dim=512 Epochs=1000 Max_ Path_ Len=3 Learning_ Rate=0.0001 Topk=500, The parameter 'Open Paths Sampling Ratio' should be set to 0.1, but I cannot find the corresponding position in the code.
> 
> After following the above configuration, I successively ran "main. py" and "kg_completion. py", but the replication effect was poor.
> 
> What are the meanings of the parameters' sparsity ',' alpha ',' anchor ',' learned_path_len ', and' top 'and' threshold 'in' main. py 'and' kg_completion. py '? Do you follow the initial settings?

Hello,When you run main.py, do you encounter the problem that one of the variables in loss.backward is modified in place, resulting in an error in gradient calculation? The specific error message is as follows: “RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [50, 1, 25]], which is output 0 of DivBackward0,is at version 1; expected version 0 instead”....I re-checked the code in model.py when processing seq_len>2, and modified the output operation to avoid in-place operations, but this error still occurred.
