### ISSUE TITLE
Some clarifications on datasets

### ISSUE THREAD

**Issue by niteshroyal** [vivian1993/NCRL#6]
Dear Vivian,

I found the paper very interesting.

I have some questions regarding the dataset.

In each dataset, you have "facts.txt", "train.txt", "test.txt", and "valid.txt". After reading the README file, I understood that the rules are learned using data in "train.txt" and then the rules are validated on data from "valid.txt". For final testing, only data from "test.txt" and the rules are used. 

So, what is in the "facts.txt" file? Is "facts.txt" divided into three files: "train.txt", "test.txt", and "valid.txt"?

Best regards,
Nitesh

**Comment by vivian1993** [comment]
We employ such a split following NeuralLP. In our case, you can simply merge facts.txt and train.txt together and the rules are learned using both.
