### ISSUE TITLE
Family Dataset Clarifications 

### ISSUE THREAD

**Issue by Blair-Johnson** [vivian1993/NCRL#7]
Hello, I noticed that the family dataset contains significantly more entities than the original 24 included in the Hinton paper. Would you mind explaining where the additional entities came from? Is it simply the two family tree graphs repeated over and over again, or are the graphs connected to one another? Thanks!

**Comment by vivian1993** [comment]
We follow the NeuralLP to use the family dataset. You can find more detailed at https://arxiv.org/pdf/1702.08367.pdf
